### ISSUE TITLE
Virtual hardware xtask could continue to destroy past (some?) failures

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#5697] opened 2024-05-03 07:27 UTC
The new virtual-hardware xtask is awesome. I also noticed that it bails out on the first failure while destroying the environment:

```
bnaecker@shale : ~/omicron $ cargo xtask virtual-hardware destroy
    Finished dev [unoptimized + debuginfo] target(s) in 0.87s
     Running `target/debug/xtask virtual-hardware destroy`
destroying virtual hardware
Disabling svc:/system/fmd:default
Re-enabling svc:/system/fmd:default
unloading xde driver
ensuring softnpu zone destroyed
Error: "/usr/bin/pfexec" failed: exit status: 1 (stderr: failed to halt zone config for sidecar_softnpu: Failed to parse command output: exit code 1
stdout:

stderr:
zoneadm: sidecar_softnpu: No such zone configured
failed to uninstall zone config for sidecar_softnpu: Failed to parse command output: exit code 1
stdout:

stderr:
zoneadm: sidecar_softnpu: No such zone configured
failed to delete zone config for sidecar_softnpu: Failed to parse command output: exit code 1
stdout:

stderr:
sidecar_softnpu: No such zone configured
sidecar_softnpu: No such zone configured
Error: No such file or directory (os error 2)
)
```

In this case, the previous run of the tool failed _after_ removing the softnpu zone. So that no longer exists, and the tool shows the (correct) output of `zoneadm` that agrees. It would be nice if we tried to move past some of these failures, similar to the bash scripts the xtask has replaced. I'm not sure exactly where to draw the line when deciding to continue, but in this case we certainly could. We had done this previously by first checking if the zone exists, and then deleting it if so.

**Comment by karencfv** [comment] 2024-05-05 22:43
This may be a dupe of https://github.com/oxidecomputer/omicron/issues/5566 ?

**Closed** 2024-05-05 23:04 UTC
