### ISSUE TITLE
Oximeter producer for sidecar hits "Schema mismatch for timeseries 'data_link:link_up'" error

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4220] opened 2023-10-06 01:03 UTC
Errors like this were seen on rack2 which was updated this morning from main:
```
21:33:58.422Z ERRO oximeter (oximeter-agent): timeseries schema mismatch, sample will be skipped: Schema mismatch for timeseries 'data_link:link_up', expected fields {"link_id": I64, "port_id": String, "rack_id": Uuid, "sidecar_id": Uuid, "sled_id": Uuid} found fields {"link_id": I64, "port_id": String, "rack_id": Uuid, "sidecar_id": Uuid, "sled_id": Uuid}
    collector_id = da510a57-3af1-4d2b-b2ed-2e8849f27d8b
    file = oximeter/db/src/client.rs:300
    id = ef3a153a-de65-4ba4-be3d-eee1fa152907
```

**Comment by bnaecker** [comment] 2023-10-21 20:27
This error message is extremely unhelpful, since it seems to show the same field names / values in the found and expected schema. I'm going to add a small PR which improves the error reporting in `oximeter-collector`, to hopefully smoke this out more clearly.

**Comment by david-crespo** [comment] 2023-10-21 20:33
Must be comparing them with different orders but then printing with sorted keys.

**Comment by bnaecker** [comment] 2023-10-21 20:40
Yeah, it looks like another consequence of the switch from a `Vec` to the `BTreeMap` for storing fields. Testing now.

**Comment by bnaecker** [comment] 2023-10-22 16:27
Well that's not what I expected:

```
16:19:47.512Z ERRO oximeter (oximeter-agent): timeseries schema mismatch, sample will be skipped
    actual = TimeseriesSchema { timeseries_name: TimeseriesName("data_link:link_up"), field_schema: {FieldSchema { name: "link_id", ty: I64, source: Target }, FieldSchema { name: "port_id", ty: String, source: Target }, FieldSchema { name: "rack_id", ty: Uuid, source: Target }, FieldSchema { name: "sidecar_id", ty: Uuid, source: Target }, FieldSchema { name: "sled_id", ty: Uuid, source: Target }}, datum_type: CumulativeI64, created: 2023-10-22T16:19:47.512167943Z }
    collector_id = 82b3c525-cf15-40e1-8a9d-9bf5eb4cb3af
    expected = TimeseriesSchema { timeseries_name: TimeseriesName("data_link:link_up"), field_schema: {FieldSchema { name: "link_id", ty: I64, source: Target }, FieldSchema { name: "port_id", ty: String, source: Target }, FieldSchema { name: "rack_id", ty: Uuid, source: Target }, FieldSchema { name: "sidecar_id", ty: Uuid, source: Target }, FieldSchema { name: "sled_id", ty: Uuid, source: Target }}, datum_type: Bool, created: 2023-10-20T21:20:50.954995640Z }
```

That's running on `madrid`, printing the full / raw timeseries schema in the error message, but otherwise the program is the same as `main`. Investigating.

**Comment by bnaecker** [comment] 2023-10-22 16:30
That's not a bug in the derivation of the schema from the sample, nor in the reporting of the datum type. Here's the raw sample itself:

```
16:29:12.087Z ERRO oximeter (oximeter-agent): timeseries schema mismatch, sample will be skipped
    actual = TimeseriesSchema { timeseries_name: TimeseriesName("data_link:link_up"), field_schema: {FieldSchema { name: "link_id", ty: I64, source: Target }, FieldSchema { name: "port_id", ty: String, source: Target }, FieldSchema { name: "rack_id", ty: Uuid, source: Target }, FieldSchema { name: "sidecar_id", ty: Uuid, source: Target }, FieldSchema { name: "sled_id", ty: Uuid, source: Target }}, datum_type: CumulativeI64, created: 2023-10-22T16:29:12.087788440Z }
    collector_id = 82b3c525-cf15-40e1-8a9d-9bf5eb4cb3af
    expected = TimeseriesSchema { timeseries_name: TimeseriesName("data_link:link_up"), field_schema: {FieldSchema { name: "link_id", ty: I64, source: Target }, FieldSchema { name: "port_id", ty: String, source: Target }, FieldSchema { name: "rack_id", ty: Uuid, source: Target }, FieldSchema { name: "sidecar_id", ty: Uuid, source: Target }, FieldSchema { name: "sled_id", ty: Uuid, source: Target }}, datum_type: Bool, created: 2023-10-20T21:20:50.954995640Z }
    file = oximeter/db/src/client.rs:394
    id = a74657d2-0b63-42d2-a12d-3e1271e2086a
    sample = Sample { measurement: Measurement { timestamp: 2023-10-22T16:29:11.926014260Z, datum: CumulativeI64(Cumulative { start_time: 2023-10-20T23:06:25.888054024Z, value: 1 }) }, timeseries_name: "data_link:link_up", target: FieldSet { name: "data_link", fields: {"link_id": Field { name: "link_id", value: I64(0) }, "port_id": Field { name: "port_id", value: String("qsfp0") }, "rack_id": Field { name: "rack_id", value: Uuid(0b26ba18-7ca7-42c6-8450-d0fcdcaad0c0) }, "sidecar_id": Field { name: "sidecar_id", value: Uuid(00000000-0000-0000-0802-5dbb797061d4) }, "sled_id": Field { name: "sled_id", value: Uuid(c3bce666-0593-4e24-baca-c8bd121c9cda) }} }, metric: FieldSet { name: "link_up", fields: {} } }
```

So it _looks_ like the Dendrite producer is sending us a real cumulative `i64` now.

**Comment by bnaecker** [comment] 2023-10-22 16:59
Well there's yer problem: https://github.com/oxidecomputer/dendrite/blob/5e3d9586d51082d24bd8e7eb18a1ba2fa04f9402/asic/src/tofino_asic/stats.rs#L60

**Comment by bnaecker** [comment] 2023-10-24 18:05
This is really https://github.com/oxidecomputer/dendrite/issues/661, closing since there's nothing right now to fix in Omicron.

**Closed by bnaecker** 2023-10-24 18:05 UTC
Labels: Metrics
