### ISSUE TITLE
`integration_tests::images::test_image_create_bad_image_size` appears to hang?

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3580] opened 2023-07-12 20:05 UTC
See: https://buildomat.eng.oxide.computer/wg/0/details/01H55KF6XCA5Z1T80V097PNVDA/0iF70b74n9TCKX9VEqlWnoUtcR8liH82CXObGk1Y2Ya8ZvyL/01H55KG8C022ARF2TKBJAXQ7HG

I see this in the logs:

```
5868	2023-07-12T18:37:40.660Z	test integration_tests::images::test_silo_image_create ... ok
5869	2023-07-12T18:37:55.579Z	test integration_tests::images::test_image_create_bad_image_size has been running for over 60 seconds
5870	2023-07-12T18:37:57.650Z	test integration_tests::instances::test_attach_one_disk_to_instance ... ok
```

I audited the log, and all other tests that claim to have run for over 60 seconds have completed, but this particular one seems stuck. I believe the associated PR Is unrelated to virtual disks.

**Comment by jgallagher** [comment] 2023-07-12 20:34
It looks like on https://buildomat.eng.oxide.computer/wg/0/details/01H55HYZ0D65FE0M0VFERW6DDF/LqRDmRlBcWqvBUJT4kw1nwcJCPBk7gw8Gms4gSqlPJDMsWA4/01H55J01Y32X7YK84GJ47BTQ6D#S5730 it's a slightly different (but close) test? I see

```
test integration_tests::images::test_image_create_bad_content_length has been running for over 60 seconds 
```

as the only stuck test.

**Comment by jgallagher** [comment] 2023-07-12 21:48
https://buildomat.eng.oxide.computer/wg/0/details/01H55KPK053MMS3A18V5NCEXTD/s1CE0hXujE1uH2Ey8ljt4aFpZOlebYWdZCdfKnbOo6Bv9naK/01H55KRAMWSHJSWE76XTGXRFZP is another hang on another different test:

```
2023-07-12T18:47:09.544Z | test integration_tests::silo_users::test_silo_group_detail_bad_group_id has been running for over 60 seconds

**Comment by davepacheco** [comment] 2023-07-14 20:23
Excitingly, the CI run for #3622 hit the problem we're trying to catch.  The suspicious thing I see in the log is backoffs for:

```
test_create_a_saml_idp_invalid_descriptor_truncated (oximeter): failed to initialize ClickHouse database, will retry in 219.061027595s
    error = Database(DatabaseUnavailable("error sending request for url (http://[::1]:37603/?output_format_json_quote_64bit_integers=0): error trying to connect: tcp connect error: Connection refused (os error 111)"))
```

That's from Oximeter reporting that Clickhouse isn't running.  I think test setup is stuck because we're waiting for Oximeter to start.  Following along here:
https://github.com/oxidecomputer/omicron/blob/fca839ccfcfba9efad015e79e707f1efaf8258af/nexus/test-utils/src/lib.rs#L759-L776

I think we're inside `start_oximeter()` (because we've seen "Starting Oximeter" in the log and have not seen "Starting test metric Producer Server").

Why isn't Clickhouse running?  We saw "Starting Clickhouse".  One thing that I don't yet understand is that when we create the Clickhouse server, we point it to a log file in a temp directory created by `TempDir`, which claims to use `std::env::temp_dir()`, which claims to use the TMPDIR environment variable.  That appears (from the bash script that runs this job) be set to /var/tmp/omicron_tmp and that means we should have that log file uploaded by buildomat.  But we don't.

**Comment by davepacheco** [comment] 2023-07-14 20:24
One thought: the timeout is hitting `cargo test` with SIGTERM, which may be triggering a graceful shutdown that includes dropping everything, which would clean up the temporary directory.  I'm going to keep debugging this in #3627, where I've changed it to use SIGKILL.

**Comment by jgallagher** [comment] 2023-07-15 05:20
I was able to reproduce this on Linux locally; for me it triggered on `test_instance_v2p_mappings`, and @davepacheco were able to poke around live. I'm attaching both the test log and the clickhouse server log, which we think reveals the issue:

[test_all-44507c7974f4755f-test_instance_v2p_mappings.6121.90.log](https://github.com/oxidecomputer/omicron/files/12060466/test_all-44507c7974f4755f-test_instance_v2p_mappings.6121.90.log)
[clickhouse-server.log](https://github.com/oxidecomputer/omicron/files/12060467/clickhouse-server.log)

From the test log, we see that we're trying and failing to connect to clickhouse at `http://[::1]:41375`:

```
[2023-07-15T04:35:21.715989637Z]  WARN: test_instance_v2p_mappings/oximeter/6121 on oxidian: failed to initialize ClickHouse database, will retry in 136.340748151s
    error: Database(DatabaseUnavailable("error sending request for url (http://[::1]:41375/?output_format_json_quote_64bit_integers=0): error trying to connect: tcp connect error: Connection refused (os error 111)"))
```

Is clickhouse actually listening on that port? `netstat` shows

```
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      22763/clickhouse
tcp        0      0 127.0.0.1:9004          0.0.0.0:*               LISTEN      22763/clickhouse
tcp        0      0 127.0.0.1:41375         0.0.0.0:*               LISTEN      22763/clickhouse
tcp6       0      0 ::1:33327               :::*                    LISTEN      22763/clickhouse
tcp6       0      0 ::1:9004                :::*                    LISTEN      22763/clickhouse
tcp6       0      0 ::1:9000                :::*                    LISTEN      22763/clickhouse
```

so it _is_ listening on port 41375, but over IPv4, not IPv6; the IPv6 port it's listening on is 33327. This matches the clickhouse logs:

```
2023.07.14 22:20:57.193592 [ 22763 ] {} <Information> Application: Listening for http://[::1]:33327
2023.07.14 22:20:57.265597 [ 22763 ] {} <Information> Application: Listening for http://127.0.0.1:41375
```

How do we determine what port to connect to? We [scan the clickhouse logfile](https://github.com/oxidecomputer/omicron/blob/f47fc2624bed76fb33c42fb243a33cbdc99eb19b/test-utils/src/dev/clickhouse.rs#L219-L253), looking for the needle `<Information> Application: Listening for http://` and then parsing the port number from that line. This seems fragile: we assume the first such line we find is the IPv6 port, but don't actually check that in the needle, so if the two lines above showed up in opposite order it would explain why we'd be trying 41375 instead of 33327. We should fix that fragility, but it can't explain the problem on this hang: the clickhouse log lines are in the proper order. Not only are the log lines in the proper order for success, but if we run `find_clickhouse_port_in_log()` against the `clickhouse-server.log` I pasted above, it returns 33327 as one would expect; but when the test ran, it returned 41375!

Our hypothesis is based on the use of `BufReader`, and particular our loop that attempts to handle an incomplete log file:

```rust
    loop {
        let line = lines.next_line().await?;
        match line {
            Some(line) => {
                // ... elided; check for the needle and parse a port number ...
            }
            None => {
                // Reached EOF, just sleep for an interval and check again.
                sleep(Duration::from_millis(10)).await;
            }
        }
    }
```

What would happen if we got unlucky and hit EOF partway through the key log line? In particular, if the `BufReader` hit EOF in the middle of this line:

```
2023.07.14 22:20:57.193592 [ 22763 ] {} <Information> Application: Listening for http://[::1]:33327
```

it would return the "first half" (wherever EOF happened to land) as `line`, which would not match our needle. We'd then sleep 10 ms and call `next_line()` again; it would then return the rest of the line, which would _also_ not match the needle, and we'd continue reading until we found the second matching line containing the IPv4 port.

How likely is it that we could have hit EOF right in the middle of the one line we care about? It looks like we indeed got unlucky: one might assume logfile writes show up in block-sized chunks, and exactly 4096 bytes into the log file is:

```
$ dd if=clickhouse-server.log bs=4096 skip=1 | head -n 1
plication: Listening for http://[::1]:33327
```

i.e., right in the middle of the line we care about!

I'll prep a change that:

1. Adds `[::1]` to our needle to make sure we're only finding the IPv6 port
2. Changes the logic to properly handle EOF partway through (probably by closing the file and reopening it and just rereading from the beginning)

**Closed** 2023-07-15 07:52 UTC
Labels: Test Flake
