### ISSUE TITLE
MUPdate: Seeing corrupted host OS images after update

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3441] opened 2023-06-28 00:44 UTC
After a mupdate, I'm seeing all sleds back in A0 (as expected) but the ones in cubby 9 and 11 are not showing up in `pilot host ls`.

From the serial console of cubby 9:

```
           WARNING: checksum mismatch
NOTICE:     want: df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d
NOTICE:     have: cd1fa165d8beb73a240fe79e387b2ab72670a4ffe364b867b5a95e4bdd1de5af
WARNING: boot image integrity failure want df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d got cd1fa165d8beb73a240fe79e387b2ab72670a4ffe364b867b5a95e4bdd1de5af

-----------> Sending IPCC command 0x6, attempt 1/10
Additional data length: 0xa9
Received empty frame
Additional data length: 0x0

panic[cpu0]/thread=fffffffffbe9f1e0: boot image integrity failure want df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d got cd1fa165d8beb73a240fe79e387b2ab72670a4ffe364b867b5a95e4bdd1de5af

Warning - stack not written to the dump buffer
fffffffffbea5060 boot_image:oxide_boot_locate+380 ()
fffffffffbea5090 genunix:boot_image_locate+a1 ()
fffffffffbea50d0 genunix:main+137 ()
fffffffffbea50e0 unix:_locore_start+8
```

Seeing something similar in cubby 11:
```
NOTICE: TRYING: boot disk (slot 17, slice 0)
NOTICE: found M.2 device (slot 17, slice 0), @ /pci@0,0/pci1de,fff9@1,3/pci1344,3100@0/blkdev@w00A075013280E36C,0:a
NOTICE:     in image: df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d
NOTICE: attempting boot from image name 'ci 6d5da99/46ea833 2023-06-27 17:23'
WARNING: checksum mismatch
NOTICE:     want: df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d
NOTICE:     have: 6f427a8268101361097a314a9e3544a880f257355661a28641b9ac15fe038e5a
WARNING: boot image integrity failure want df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d got 6f427a8268101361097a314a9e3544a880f257355661a28641b9ac15fe038e5a

-----------> Sending IPCC command 0x6, attempt 1/10
Additional data length: 0xa9
Received empty frame
Additional data length: 0x0

panic[cpu0]/thread=fffffffffbe9f1e0: boot image integrity failure want df81ccd1e6e9d4169d56636e50d897116c756c23cf012dffdeaf88742b3d015d got 6f427a8268101361097a314a9e3544a880f257355661a28641b9ac15fe038e5a

Warning - stack not written to the dump buffer
fffffffffbea5060 boot_image:oxide_boot_locate+380 ()
fffffffffbea5090 genunix:boot_image_locate+a1 ()
fffffffffbea50d0 genunix:main+137 ()
fffffffffbea50e0 unix:_locore_start+88 ()
```

Note that after another round of mupdate - using the same TUF repo - this issue went away. This is possibly a sign of a partial write?

@jgallagher , @leftwo

**Comment by citrus-it** [comment] 2023-06-28 07:11
installinator writes the image to both M.2s I think, in which case it would hopefully be possible to switch BSUs and see if the other one boots (and then grab the image from each M.2 and compare).

**Comment by bcantrill** [comment] 2023-07-04 06:48
We saw this again, this time on sled 17. Here is [a dump of the SP as it was found](https://github.com/oxidecomputer/omicron/files/11945562/hubris.core.sled-17.wtf.zip); forcing it to A0 and it was failing to boot:

```console
Oxide Pico Host Boot Loader
Config {
    cons:   Uart(fedc9000),
    loader: 0x7f537000..0x7fff0000
    pageroot: P4KA(0x7ff6f000),
}
Decompressing cpio archive to 0x77537000..0x7f537000...Done.
jumping to kernel entry at 0xfffffffffbc28fb0
Configured AGPIO139: 50300 (input is high)
Socket 0 SMU Version: 45.93.0
Socket 0 DXIO Version: 45.682
Socket 0 SMU features 0x0690fbfd enabled
cpu0: microcode has been updated from version 0x0 to 0xa0011ce
Oxide Helios Version stlouis-0-g37d856a03c 64-bit (onu)
NOTICE: Starting Oxide boot
NOTICE:     Phase 1 wants: 0526b2cc8a2f2d4b52a5175b1f908af862430e3ba09cd79fc7fb04e868982596
NOTICE: TRYING: boot sp
WARNING: first block too small for disk header, got 0x0

-----------> Sending IPCC command 0x6, attempt 1/10
Additional data length: 0x30
Received empty frame
Additional data length: 0x0
WARNING: Could not find a valid phase2 image on sp

-----------> Sending IPCC command 0x6, attempt 1/10
Additional data length: 0x2b
Received empty frame
Additional data length: 0x0

panic[cpu0]/thread=fffffffffbe9f1e0: Could not find a valid phase2 image on sp

Warning - stack not written to the dump buffer
fffffffffbea5060 boot_image:oxide_boot_locate+18a ()
fffffffffbea5090 genunix:boot_image_locate+a1 ()
fffffffffbea50d0 genunix:main+137 ()
fffffffffbea50e0 unix:_locore_start+88 ()

skipping system dump - no dump device configured
```


And an update was frozen:

```console
root@oxz_switch:/var/tmp# ./faux-mgs --interface gimlet17 update-status host-boot-flash
Jan 02 10:02:11.332 INFO creating SP handle on interface gimlet17, component: faux-mgs
Jan 02 10:02:11.358 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:182%60]:11111, interface: gimlet17, component: faux-mgs
Jan 02 10:02:11.374 INFO update f6ba7068-7460-4b27-b538-7458c04b2d6b in progress (22633854 of 33554432 received)update f6ba7068-7460-4b27-b538-7458c04b2d6b in progress (22633854 of 33554432 received)
, component: faux-mgs
root@oxz_switch:/var/tmp# ./faux-mgs --interface gimlet17 update-status host-boot-flash
Jan 02 10:02:15.287 INFO creating SP handle on interface gimlet17, component: faux-mgs
Jan 02 10:02:15.288 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:182%60]:11111, interface: gimlet17, component: faux-mgs
Jan 02 10:02:15.289 INFO update f6ba7068-7460-4b27-b538-7458c04b2d6b in progress (22633854 of 33554432 received), update f6ba7068-7460-4b27-b538-7458c04b2d6b in progress (22633854 of 33554432 received)
```

This system has booted the [recovery image](https://github.com/oxidecomputer/meta/blob/master/engineering/sled-recovery.md) and is being left for further analysis.

**Comment by leftwo** [comment] 2023-07-04 14:10
I put wicketd logs from gimlet 16's switch zone here: `/net/catacomb/data/staff/core/rack2/omicron-3441/`
oxide-wicketd:default.log and oxide-wicketd:default.log.0

**Comment by citrus-it** [comment] 2023-07-05 10:23
> NOTICE: TRYING: boot sp
> WARNING: first block too small for disk header, got 0x0

This means that the SP is still configured to tell the host to boot via IPCC, and that there was no answering [faux-]mgs to provide the image.
Best guess (although cannot be sure without having seen the M.2s, and it appears to have been rebuilt since) is that wicket got as far as getting installinator running, and then powered off after it completed, but failed to write the new phase 1 to the SPI flash.

**Comment by askfongjojo** [comment] 2023-07-11 20:15
Related to #3507 which is being actively worked on.

**Comment by jgallagher** [comment] 2023-07-13 21:28
We strongly believe this was caused by https://github.com/oxidecomputer/stlouis/issues/454 which is now fixed; closing (and if we see a similar issue in the future it will need new investigation).

**Closed by jgallagher** 2023-07-13 21:28 UTC
