### ISSUE TITLE
Ability for silo user to see which IP pool is the silo default

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4817] opened 2024-01-15 23:31 UTC
It'll be helpful to present the `is_default` attribute to silo users so that they know which IP pool is used by default when interpreting the results from `/v1/ip-pools` or `oxide ip-pool list`.

**Comment by david-crespo** [comment] 2024-01-15 23:36
Duplicate of #4752

**Closed by david-crespo** 2024-01-15 23:36 UTC
