### ISSUE TITLE
test failed in CI: test_multiple_disks_multiple_snapshots_order_2

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#7249] opened 2024-12-13 20:42 UTC
This test failed on a CI run on **pull request #7138**:
https://github.com/oxidecomputer/omicron/runs/34394404020

I think this is unrelated to the changes in that PR because I only changed the `ls-apis` tool, not anything in this neighborhood.

Log showing the specific test failure:

https://buildomat.eng.oxide.computer/wg/0/details/01JF0RCBH9RD8E4F92Y5NHJ6EX/9bWlMr7fnay0pmWwSXgD0pCW1BMJ06BVquYU3TI3gtDf9Gza/01JF0RCVASHQ470V2HSW1RGGFR#S6804

Excerpt from the log showing the failure:

```
        FAIL [  26.342s] omicron-nexus::test_all integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2
--- STDOUT:              omicron-nexus::test_all integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2 ---
running 1 test
test integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2 ... FAILED
failures:
failures:
    integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 399 filtered out; finished in 26.27s
--- STDERR:              omicron-nexus::test_all integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2 ---
log file: /var/tmp/omicron_tmp/test_all-3ff1fbb3e60a0b4e-test_multiple_disks_multiple_snapshots_order_2.208545.0.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-3ff1fbb3e60a0b4e-test_multiple_disks_multiple_snapshots_order_2.208545.0.log"
DB URL: postgresql://root@[::1]:35907/omicron?sslmode=disable
DB address: [::1]:35907
log file: /var/tmp/omicron_tmp/test_all-3ff1fbb3e60a0b4e-test_multiple_disks_multiple_snapshots_order_2.208545.2.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-3ff1fbb3e60a0b4e-test_multiple_disks_multiple_snapshots_order_2.208545.2.log"
log file: /var/tmp/omicron_tmp/test_all-3ff1fbb3e60a0b4e-test_multiple_disks_multiple_snapshots_order_2.208545.3.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-3ff1fbb3e60a0b4e-test_multiple_disks_multiple_snapshots_order_2.208545.3.log"
thread 'integration_tests::volume_management::test_multiple_disks_multiple_snapshots_order_2' panicked at nexus/tests/integration_tests/volume_management.rs:720:5:
assertion failed: disk_test.crucible_resources_deleted().await
```

**Comment by jgallagher** [comment] 2024-12-13 21:07
Dupe of #7071, I believe!

**Closed by jgallagher** 2024-12-13 21:07 UTC
Labels: Test Flake

**Comment by davepacheco** [comment] 2024-12-13 22:06
Oops, sorry!  Not sure how I missed it.
