### ISSUE TITLE
generate debug symbols for release builds

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/omicron#1280] opened 2022-06-25 05:38 UTC
Rust has the ability to generate DWARF information for release builds, which is invaluable when debugging.  To turn this on, we need to set `debug` to `2` under the `release` profile:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index fc2e036d..07ed70a0 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -64,6 +64,7 @@ panic = "abort"
 
 [profile.release]
 panic = "abort"
+debug = 2
 
 #
 # It's common during development to use a local copy of dropshot, propolis
```

The binary gets much larger (from ~45M to ~475M) but the loaded size doesn't change (and the binaries could always be stripped to a smaller size if/when needed).

**Comment by jordanhendricks** [comment] 2023-08-11 03:53
I didn't know this ticket existed when I filed #3768. Going to close this issue as a dupe of that, since there will be some more details there to figure out with regard to shipping symbols for binaries in the ramdisk.

**Closed by jordanhendricks** 2023-08-11 03:53 UTC
