### ISSUE TITLE
Validate `idp_entity_id` from SAML descriptor xml, or just pull it out automatically

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/omicron#3725] opened 2023-07-20 19:32 UTC
Our SAML IdP creation parameter has a `idp_entity_id` field, but that can be different from what the IdP's descriptor XML has for `md:EntityDescriptor entityID`. Either validate that the entity ID is the same or automatically pull it out of the descriptor and remove it as a parameter.

**Comment by luqmana** [comment] 2023-07-20 19:43
Dupe of #3049

**Closed** 2023-07-20 19:56 UTC
