### ISSUE TITLE
Sled-agent service creation ignores the provided addresses

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#6651] opened 2024-09-24 16:23 UTC
I was doing some work in the sled-agent services management code, and I noticed a common pattern:

https://github.com/oxidecomputer/omicron/blob/45813be40b62167eff75333c410515e8bee24211/sled-agent/src/services.rs#L1566-L1580

Here, we're matching on the type of zone we've been asked to provision, and then creating it. The zone type details include a socket address on which the provisioned service ought to be listening. However, in this example, and every other one I looked at, the sled-agent ignores that requested address and instead assumes the service is listening on the default port, e.g., `CLICKHOUSE_HTTP_PORT` in this case.

It's not wrong exactly, since all the services today do use their defaults like this. But it seems both confusing and could cause future errors if we do change those addresses or ports. We may want to have the sled-agent operate on the addresses in the `OmicronZoneType` it's been provided.

**Comment by jgallagher** [comment] 2024-09-24 17:22
> We may want to have the sled-agent operate on the addresses in the OmicronZoneType it's been provided.

To throw another idea into the ring: does every `OmicronZoneType` variant include what is effectively a duplicate of its containing `OmicronZoneConfig`'s `underlay_address`? If so, could we just delete one of them? I think right now we have many places that assume they're the same (as in the snippet you posted, where we use `underlay_address` and ignore the `address` inside `OmicronZoneType::Clickhouse`), and dropping one or the other would address most of the confusion I've had around this, I think.

**Closed** 2024-10-24 22:29 UTC
Labels: Sled Agent
