### ISSUE TITLE
Instance creation: Want ability to select a subset of SSH keys to be inserted into authorized_keys file

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#3734] opened 2023-07-21 05:38 UTC
Currently all SSH keys configured for the user who creates the instance will be automatically passed in the cloud-init metadata. At least one of our customers would like to have the option to select which SSH key(s) to include - something that many cloud providers support.

**Comment by david-crespo** [comment] 2023-07-21 05:41
Select per instance at create time?

**Comment by askfongjojo** [comment] 2023-07-21 05:41
> Select per instance at create time?

Yes, I should have been clearer about this.

**Comment by benjaminleonard** [comment] 2023-07-21 08:26
I think a dupe of #3056

**Closed** 2023-07-21 15:51 UTC
